server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/naturegram
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgresql.PostgreSQLSpatialDialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
